name: charmera_exif_fixer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  gap: ^3.0.1
  native_exif: ^0.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_storage:
    path: ./packages/shared_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
